---

- name: Debian | Disable pinned Docker version
  file:
    dest: "/etc/apt/preferences.d/docker.pref"
    state: "absent"
  when: not docker__version | d()

- name: Debian | Enable pinned Docker version
  template:
    src: "etc/apt/preferences.d/docker.pref.j2"
    dest: "/etc/apt/preferences.d/docker.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  when: docker__version | d()

- name: Debian | Install Docker's dependencies
  apt:
    name: "{{ docker__package_dependencies + docker__pip_dependencies }}"

- name: Debian | Add Docker's public GPG key to the APT keyring
  apt_key:
    id: "{{ docker__apt_key_id }}"
    url: "{{ docker__apt_key_url }}"

- name: Debian | Configure Docker's upstream APT repository
  apt_repository:
    repo: "{{ docker__apt_repository }}"
    update_cache: true

- name: Debian | Install Docker
  apt:
    name: "docker-{{ docker__edition }}"
    state: "{{ docker__state }}"

- name: Debian | Install Python packages
  pip:
    name: >
      {{ item.name }}{% if item.version | d() %}=={{ item.version }}{% endif %}
    virtualenv: "{{ docker__pip_virtualenv }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ docker__default_pip_packages + docker__pip_packages }}"
  when: item.name | d()    

